"use client";

/**
 * V0 IMPORT INSTRUCTIONS
 * Save as components/milton-schedule.tsx. Import the default component into
 * the EXISTING right-hand canvas: <MiltonSchedule />.
 * Keep your existing Milton chat and app navigation exactly as they are.
 * Do not add another sidebar, chat, or full-page shell.
 *
 * This single-file component embeds the approved working HTML/CSS/JS in an
 * isolated iframe. It needs only React; no calendar packages or remote assets.
 * The iframe protects your current UI from this calendar's styles and DOM IDs.
 * Its contents are included below as editable source, not a hosted dependency.
 * Set height="100%" when the parent has a defined height, or keep the default.
 *
 * Preserved: three tabs; Today using local date; day/week/month/coach/room views;
 * classes, 1:1, room bookings, team meetings, blocked time; click booking ->
 * inline coach dropdown; day-level coach swaps; recurrence scopes; conflicts;
 * live drag/resize -> confirm; Cancel/Escape restores original placement;
 * rosters, waitlists, attendance, example credits; member booking flow.
 *
 * Prototype boundary: in-memory sample data resets on remount/reload. No live
 * database, payments, calendar sync, outbound messaging, public booking link,
 * or integration with the existing parent chat. Wire those to your real app
 * before treating this as production scheduling. Staff/member preview is not
 * a security boundary. Existing chat can remain visible alongside this module.
 * Native React conversion is optional future integration work, not included.
 */

export default function MiltonSchedule({
  className,
  height = "calc(100dvh - 100px)",
}) {
  return (
    <iframe
      title="Milton scheduling workspace"
      className={className}
      srcDoc={SCHEDULE_DOCUMENT}
      sandbox="allow-scripts"
      style={{ width: "100%", height, minHeight: 480, border: 0, display: "block", background: "#fff" }}
    />
  );
}

const WORKSPACE_HTML = [
  "",
  "",
  "<main>",
  "<nav class=\"workspace-tabs\" aria-label=\"Scheduling workspace\"><button class=\"navitem active\" data-page=\"calendar\">Calendar</button><button class=\"navitem\" data-page=\"services\">Services</button><button class=\"navitem\" data-page=\"settings\">Setup</button><div class=\"tabtools\"><button id=\"previewBooking\">Preview</button><button id=\"shareBooking\" class=\"hidden\">Share &amp; embed</button><button class=\"primary\" id=\"newEvent\" aria-label=\"New booking\" title=\"New booking\">＋ New booking</button><button class=\"history-button\" data-page=\"activity\" aria-label=\"Activity history\">History <b id=\"activityCount\">0</b></button></div></nav>",
  "<section id=\"calendarPage\">",
  "<div class=\"toolbar\"><div class=\"datecontrols\"><button id=\"prev\" aria-label=\"Previous period\">‹</button><button id=\"next\" aria-label=\"Next period\">›</button><button id=\"today\">Today</button><h2 id=\"dateLabel\"></h2></div><div class=\"views\" role=\"group\" aria-label=\"Calendar view\"><button data-view=\"day\">Day</button><button data-view=\"week\" class=\"active\">Week</button><button data-view=\"month\">Month</button><button data-view=\"coaches\">Coaches</button><button data-view=\"rooms\">Rooms</button></div></div>",
  "<div class=\"filters\"><select id=\"typeFilter\" aria-label=\"Booking type\"></select><select id=\"coachFilter\" aria-label=\"Coach\"></select><select id=\"roomFilter\" aria-label=\"Room\"></select><select id=\"colorBy\" aria-label=\"Color events by\"><option value=\"type\">Color by type</option><option value=\"coach\">Color by coach</option></select><select id=\"audience\" aria-label=\"Calendar audience\"><option value=\"staff\">Staff calendar</option><option value=\"member\">Member calendar</option></select><select id=\"member\" class=\"hidden\" aria-label=\"Preview as member\"></select><span id=\"summary\"></span></div>",
  "<div class=\"legend\" id=\"legend\"></div>",
  "<div class=\"workspace\"><div class=\"calendar-scroll\" id=\"calendarScroll\"><div id=\"calendar\"></div></div><aside class=\"detail hidden\" id=\"detail\" aria-label=\"Booking details\"></aside></div>",
  "<footer>Click an empty time to book • Drag a card to move • Drag its bottom edge to resize • Edit also works with keyboard and touch</footer>",
  "</section>",
  "<section id=\"otherPage\" class=\"hidden\"></section>",
  "</main>",
  "<dialog id=\"dialog\"><form id=\"editor\"><div class=\"dialoghead\"><div><span class=\"eyebrow\" id=\"dialogEyebrow\">SCHEDULE</span><h2 id=\"dialogTitle\">New booking</h2></div><button type=\"button\" id=\"closeDialog\" aria-label=\"Close dialog\">×</button></div><div id=\"dialogBody\"></div><div id=\"formError\" role=\"alert\"></div><div class=\"dialogfoot\"><button type=\"button\" id=\"cancelDialog\">Cancel</button><button type=\"submit\" class=\"primary\" id=\"confirmDialog\">Save</button></div></form></dialog>",
  "<div id=\"toast\" role=\"status\"></div>",
  "",
  ""
].join("\n");
const WORKSPACE_CSS = [
  ":root{font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; color: rgb(24, 48, 51); background: rgb(255, 255, 255); font-size: 16px; --teal: #08796b; --line: #dce7e4; --muted: #627a7b; --nav: #102f32;}",
  "*{box-sizing: border-box;}",
  "body{margin: 0px; display: flex; height: 100dvh; overflow: hidden;}",
  "button,input,select,textarea{font: inherit;}",
  "button{cursor: pointer;}",
  "button,select{border: 1px solid var(--line); border-radius: 8px; background: white; color: rgb(37, 73, 75); padding: 9px 12px; font-size: 14px;}",
  "button:hover{background: rgb(238, 246, 243); border-color: rgb(171, 201, 193);}",
  "button:disabled{opacity: 0.5; cursor: not-allowed;}",
  "button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline: 3px solid #42b9aa; outline-offset: 2px;}",
  "button.primary{background: var(--teal); border-color: var(--teal); color: white; font-weight: 700;}",
  "button.primary:hover{background: rgb(5, 103, 88);}",
  "button.danger{color: rgb(181, 54, 48); border-color: rgb(229, 181, 177);}",
  "button.quiet{border: medium; background: none;}",
  ".hidden{display: none !important;}",
  "",
  "",
  "",
  "",
  ".navitem{display: flex; gap: 10px; align-items: center; background: none; border: 0px; color: rgb(194, 216, 212); text-align: left; padding: 12px 13px; margin-bottom: 6px;}",
  ".navitem:hover,.navitem.active{background: rgb(36, 80, 82); color: white;}",
  ".navitem b{font-size: 12px; margin-left: auto; background: rgb(60, 101, 100); border-radius: 4px; padding: 2px 5px;}",
  "",
  "",
  ".avatar{display: grid; place-items: center; width: 32px; height: 32px; flex: 0 0 auto; border-radius: 50%; background: rgb(220, 172, 108); color: rgb(24, 60, 57); font-weight: 750; font-size: 12px;}",
  "main{min-width: 0px; flex: 1 1 0%; display: flex; flex-direction: column;}",
  "header{display: flex; align-items: center; justify-content: space-between; gap: 12px; padding: 19px 26px 17px; border-bottom: 1px solid var(--line);}",
  ".eyebrow{font-size: 11px; letter-spacing: 1.4px; font-weight: 750; color: var(--muted);}",
  "h1{font-size: 25px; letter-spacing: -0.7px; margin: 2px 0px 0px;}",
  "h2{margin: 0px; font-size: 19px; letter-spacing: -0.3px;}",
  "h3{margin: 0px 0px 8px; font-size: 17px;}",
  ".headtools{display: flex; align-items: center; gap: 10px;}",
  ".demo{font-size: 12px; font-weight: 700; background: rgb(236, 245, 242); padding: 7px 10px; border-radius: 25px; color: rgb(36, 115, 101);}",
  ".demobar{padding: 8px 26px; display: flex; align-items: center; justify-content: space-between; background: rgb(243, 248, 246); font-size: 12px; color: rgb(80, 110, 105); gap: 10px;}",
  ".demobar button{font-size: 12px; padding: 3px 8px; background: none; border: 0px; text-decoration: underline; white-space: nowrap;}",
  "#calendarPage{display: flex; flex: 1 1 0%; min-height: 0px; flex-direction: column;}",
  ".toolbar{display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; padding: 15px 22px 10px; gap: 12px;}",
  ".datecontrols{display: flex; gap: 6px; align-items: center;}",
  ".datecontrols h2{margin-left: 10px; font-size: 18px;}",
  ".datecontrols>button:first-child,.datecontrols>button:nth-child(2){font-size: 20px; padding: 4px 12px;}",
  ".views{display: flex; border: 1px solid var(--line); border-radius: 8px; overflow: hidden;}",
  ".views button{border: 0px; border-radius: 0px; font-size: 14px;}",
  ".views button.active{background: rgb(220, 242, 233); color: var(--teal); font-weight: 750;}",
  ".filters{padding: 0px 22px 10px; display: flex; flex-wrap: wrap; align-items: center; gap: 8px;}",
  ".filters select{font-size: 13px; padding: 8px;}",
  ".filters #summary{margin-left: auto; font-size: 12px; color: var(--muted);}",
  ".legend{display: flex; flex-wrap: wrap; gap: 16px; padding: 0px 24px 12px; font-size: 12px; color: rgb(93, 117, 115);}",
  ".legend span{display: flex; align-items: center; gap: 6px;}",
  ".swatch{width: 8px; height: 8px; border-radius: 3px; display: inline-block;}",
  ".workspace{flex: 1 1 0%; min-height: 0px; display: flex; border-top: 1px solid var(--line);}",
  ".calendar-scroll{overflow: auto; flex: 1 1 0%; min-width: 0px; position: relative; overscroll-behavior: contain;}",
  ".timegrid{display: grid; min-width: 870px; grid-template-columns: 54px repeat(var(--cols),minmax(112px,1fr)); align-items: start;}",
  ".gridhead{height: 57px; position: sticky; top: 0px; z-index: 5; border-right: 1px solid var(--line); border-bottom: 1px solid var(--line); background: rgb(250, 253, 251); text-align: center; padding: 10px 4px; font-size: 13px; font-weight: 700;}",
  ".gridhead small{display: block; font-size: 12px; color: var(--muted); margin-top: 4px; font-weight: 400;}",
  ".gridhead.focusday{background: rgb(230, 245, 238); color: rgb(6, 116, 102);}",
  ".ruler{position: relative; height: 1008px; background: rgb(252, 253, 252); border-right: 1px solid var(--line);}",
  ".ruler span{position: absolute; right: 8px; font-size: 11px; color: var(--muted); transform: translateY(4px);}",
  ".lane{height: 1008px; position: relative; border-right: 1px solid var(--line); background: repeating-linear-gradient(transparent 0, transparent 35px, rgb(238, 243, 241) 35px, rgb(238, 243, 241) 36px, transparent 36px, transparent 71px, rgb(223, 233, 229) 71px, rgb(223, 233, 229) 72px);}",
  ".lane:hover{background-color: rgb(252, 254, 253);}",
  ".lane.dragover{background-color: rgb(224, 243, 235);}",
  ".event{position: absolute; border-left: 3px solid var(--edge); border-radius: 7px; background: var(--tint); color: var(--text); padding: 0px; overflow: hidden; display: flex; flex-direction: column; box-shadow: 0 1px 3px #173d3410; z-index: 2; min-height: 20px;}",
  ".event:hover{box-shadow: 0 3px 8px #183e3820; z-index: 4;}",
  ".event.selected{outline: 2px solid var(--edge); outline-offset: 1px;}",
  ".eventmain{color: inherit; background: none; border: 0px; padding: 5px 7px 2px; display: block; text-align: left; min-height: 0px; overflow: hidden; line-height: 1.2; font-size: 13px; width: 100%; flex: 1 1 0%; touch-action: pan-y;}",
  ".eventmain:hover{background: transparent; border: 0px;}",
  ".eventmain strong{font-size: 13px; display: block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; margin: 2px 0px;}",
  ".eventmain small{font-size: 11px; display: block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;}",
  ".eventmeta{display: flex; justify-content: space-between; gap: 3px; font-size: 11px; white-space: nowrap; overflow: hidden;}",
  ".event .grip{position: absolute; right: 1px; top: 1px; background: var(--tint); border: 0px; color: var(--edge); padding: 0px 3px; font-size: 12px; cursor: grab; touch-action: none; opacity: 0.5;}",
  ".event:hover .grip{opacity: 1;}",
  ".resize{height: 7px; cursor: ns-resize; touch-action: none; flex: 0 0 auto; border: 0px; padding: 0px; border-radius: 0px; width: 100%;}",
  ".resize:after{content: \"\"; display: block; width: 19px; height: 2px; background: var(--edge); opacity: 0.4; margin: 2px auto;}",
  ".event.zero{border-style: dashed;}",
  ".ghost{position: fixed; z-index: 60; pointer-events: none; border: 2px solid var(--teal); background: rgba(228, 245, 237, 0.933); padding: 10px; border-radius: 8px; font-size: 13px; box-shadow: 0 8px 35px #123d3430; min-width: 150px;}",
  ".detail{width: 326px; flex: 0 0 auto; border-left: 1px solid var(--line); background: rgb(252, 254, 252); overflow: auto; padding: 20px;}",
  ".detail>h2{margin: 7px 0px 5px; font-size: 21px;}",
  ".detail .close{float: right; padding: 0px 5px; font-size: 24px; border: 0px; background: none;}",
  ".sub{color: var(--muted); font-size: 13px; line-height: 1.5; margin: 4px 0px;}",
  ".badge{display: inline-block; font-size: 12px; font-weight: 700; border-radius: 20px; background: rgb(229, 244, 236); padding: 5px 9px; color: rgb(36, 114, 96); margin: 10px 0px;}",
  ".badge.warn{background: rgb(255, 240, 215); color: rgb(128, 89, 20);}",
  ".section{border-top: 1px solid var(--line); margin-top: 16px; padding-top: 16px;}",
  ".kv{display: flex; justify-content: space-between; gap: 10px; font-size: 14px; margin: 12px 0px;}",
  ".kv span{color: var(--muted);}",
  ".kv b{text-align: right;}",
  ".buttons{display: flex; gap: 8px; flex-wrap: wrap; margin-top: 12px;}",
  ".buttons>*{flex: 1 1 0%; font-size: 13px;}",
  ".rosteritem{display: flex; gap: 8px; align-items: center; border-bottom: 1px solid rgb(231, 239, 235); padding: 9px 0px; font-size: 13px;}",
  ".rosteritem .persontext{flex: 1 1 0%; min-width: 0px;}",
  ".rosteritem small{display: block; color: var(--muted); font-size: 11px; margin-top: 3px;}",
  ".rosteritem select{font-size: 12px; padding: 5px; max-width: 110px;}",
  ".rosteritem button{padding: 4px 7px;}",
  ".progress{height: 5px; background: rgb(228, 235, 232); border-radius: 10px; margin: 8px 0px;}",
  ".progress span{height: 100%; display: block; background: var(--teal); border-radius: 10px;}",
  ".note{font-size: 13px; background: rgb(239, 245, 241); border-radius: 8px; padding: 11px; color: rgb(79, 109, 100); line-height: 1.5;}",
  ".note.alert{background: rgb(255, 242, 220); color: rgb(115, 82, 26);}",
  "footer{padding: 8px 22px; border-top: 1px solid var(--line); font-size: 12px; color: var(--muted);}",
  ".monthgrid{display: grid; grid-template-columns: repeat(7,minmax(100px,1fr)); min-width: 770px;}",
  ".monthcell{min-height: 146px; border-right: 1px solid var(--line); border-bottom: 1px solid var(--line); padding: 8px; overflow: hidden;}",
  ".monthcell.off{background: rgb(246, 249, 247);}",
  ".monthcell>button{border: medium; font-weight: 700; padding: 4px; background: none;}",
  ".monthEvent{display: block !important; background: var(--tint) !important; color: var(--text) !important; border-left: 3px solid var(--edge) !important; text-align: left; width: 100%; margin: 4px 0px; border-radius: 4px !important; font-size: 12px !important; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;}",
  ".pagecontent{overflow: auto; padding: 28px; background: rgb(248, 251, 249); flex: 1 1 0%;}",
  ".pagehead{display: flex; justify-content: space-between; align-items: center; gap: 10px; margin-bottom: 22px;}",
  ".cards{display: grid; grid-template-columns: repeat(auto-fit,minmax(260px,1fr)); gap: 16px;}",
  ".card{background: white; border: 1px solid var(--line); border-radius: 12px; padding: 20px;}",
  ".card p{font-size: 14px; color: var(--muted);}",
  ".cardfoot{border-top: 1px solid var(--line); padding-top: 13px; margin-top: 16px; display: flex; justify-content: space-between; align-items: center; font-size: 13px;}",
  ".setting{display: flex; align-items: center; justify-content: space-between; padding: 16px 0px; border-bottom: 1px solid var(--line); gap: 15px; font-size: 14px;}",
  ".setting small{display: block; color: var(--muted); margin-top: 5px;}",
  ".setting input{width: 20px; height: 20px; accent-color: var(--teal);}",
  ".activity{padding: 15px; background: white; border: 1px solid var(--line); border-radius: 10px; margin-top: 12px; font-size: 14px;}",
  ".activity small{display: block; margin-top: 5px; color: var(--muted);}",
  "dialog{padding: 0px; border: medium; border-radius: 16px; box-shadow: 0 24px 100px #153b3950; max-width: 650px; width: calc(100% - 32px); max-height: 90dvh; overflow: auto; color: rgb(24, 48, 51);}",
  "dialog::backdrop{background: rgba(11, 41, 43, 0.6);}",
  ".dialoghead{padding: 22px 24px 15px; display: flex; align-items: start; justify-content: space-between; border-bottom: 1px solid var(--line);}",
  ".dialoghead h2{margin-top: 5px; font-size: 23px;}",
  ".dialoghead button{border: medium; font-size: 24px; padding: 0px; background: none;}",
  "#dialogBody{padding: 20px 24px;}",
  ".formgrid{display: grid; grid-template-columns: 1fr 1fr; gap: 14px;}",
  ".field{display: flex; flex-direction: column; gap: 7px; font-size: 14px; font-weight: 600;}",
  ".field input,.field select,.field textarea{width: 100%; padding: 10px; border: 1px solid rgb(204, 219, 214); border-radius: 8px; background: white; font-size: 15px; font-weight: 400; color: rgb(35, 65, 63);}",
  ".field textarea{min-height: 72px; resize: vertical;}",
  ".full{grid-column: 1/-1;}",
  ".check{display: flex; align-items: center; gap: 8px; font-size: 14px; font-weight: 400;}",
  ".check input{accent-color: var(--teal); width: 17px; height: 17px;}",
  ".checkgroup{display: flex; flex-wrap: wrap; gap: 12px;}",
  ".scope{display: grid; gap: 8px; margin: 15px 0px;}",
  ".scope label{display: flex; gap: 9px; align-items: center; padding: 11px; border: 1px solid var(--line); border-radius: 8px; font-size: 14px;}",
  ".scope label:has(input:checked){background: rgb(234, 247, 240); border-color: rgb(93, 184, 160);}",
  "#formError{color: rgb(160, 49, 44); font-size: 14px; line-height: 1.5; padding: 0px 24px;}",
  "#formError:not(:empty){padding: 12px 24px; background: rgb(255, 241, 238);}",
  ".dialogfoot{display: flex; gap: 9px; justify-content: flex-end; padding: 16px 24px; border-top: 1px solid var(--line); position: sticky; bottom: 0px; background: white;}",
  "#toast{position: fixed; bottom: 22px; left: 50%; transform: translateX(-50%); background: rgb(17, 63, 56); color: white; border-radius: 10px; padding: 12px 18px; z-index: 100; display: none; font-size: 14px; max-width: 90vw;}",
  "#toast.show{display: block;}",
  ".dragging{user-select: none; cursor: grabbing !important;}",
  "@media (min-width:1550px) {.eventmain strong{font-size: 14px;}",
  ".eventmain small,.eventmeta{font-size: 12px;}}",
  "@media (max-width:1150px) {",
  "",
  ".navitem span,.navitem b{display: none;}",
  ".navitem{justify-content: center; font-size: 20px;}",
  "",
  ".detail{width: 310px;}",
  ".headtools .demo{display: none;}}",
  "@media (max-width:760px) {",
  "header{padding: 14px; flex-wrap: wrap;}",
  "h1{font-size: 23px;}",
  ".headtools{gap: 7px;}",
  ".headtools select{max-width: 145px; font-size: 13px;}",
  ".demobar{padding: 7px 14px; font-size: 11px;}",
  ".toolbar{padding: 12px 14px 8px;}",
  ".datecontrols h2{font-size: 16px;}",
  ".views{width: 100%;}",
  ".views button{flex: 1 1 0%; padding: 8px; font-size: 13px;}",
  ".filters{padding: 0px 14px 10px;}",
  ".filters select{max-width: 155px;}",
  ".filters #summary{display: none;}",
  ".legend{padding: 0px 14px 9px; gap: 9px; font-size: 11px;}",
  ".detail{position: fixed; right: 0px; top: 0px; bottom: 0px; z-index: 30; width: min(360px, 100%); box-shadow: -10px 0 60px #123c3440;}",
  ".timegrid{min-width: 840px;}",
  ".timegrid.daygrid{min-width: 320px;}",
  "footer{font-size: 11px; padding: 7px 14px;}",
  ".formgrid{grid-template-columns: 1fr;}",
  ".full{grid-column: auto;}",
  ".pagecontent{padding: 18px 14px;}",
  ".headtools .primary{padding: 9px; font-size: 13px;}",
  ".calendar-scroll{touch-action: pan-x pan-y;}}",
  ":root{--teal: #116276; --line: #dce6e6; --muted: #637e7e; color: rgb(34, 49, 53); background: rgb(238, 243, 242);}",
  "body{padding: 14px; gap: 12px; background: rgb(238, 243, 242);}",
  "main{border: 1px solid var(--line); border-radius: 24px; background: rgb(255, 255, 255); overflow: hidden; box-shadow: 0 4px 20px #21444706;}",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  ".workspace-title{display: flex; align-items: center; gap: 12px;}",
  "header{padding: 18px 24px; border: 0px; min-height: 86px;}",
  ".headtools{flex-wrap: wrap; justify-content: flex-end;}",
  ".headtools button{border-radius: 24px; font-weight: 650;}",
  "h1{font-size: 26px;}",
  ".eyebrow{font-size: 12px;}",
  ".workspace-tabs{display: flex; align-items: center; gap: 22px; padding: 0px 24px; border-bottom: 1px solid var(--line); overflow: auto; flex: 0 0 auto;}",
  ".tabtools{margin-left: auto; display: flex; align-items: center; gap: 10px;}",
  ".tabtools button{border-radius: 24px; font-weight: 650; font-size: 13px; padding: 8px 14px; white-space: nowrap;}",
  ".tabtools .history-button{margin-left: 4px; border-radius: 0px; padding: 8px 4px;}",
  ".workspace-tabs .navitem{display: flex; white-space: nowrap; border-radius: 0px; color: rgb(106, 125, 127); padding: 13px 0px; margin: 0px; font-size: 14px; border-bottom: 3px solid transparent; justify-content: center;}",
  ".workspace-tabs .navitem.active{color: var(--teal); border-bottom-color: var(--teal); background: transparent; font-weight: 750;}",
  ".workspace-tabs .navitem:hover{background: transparent; color: var(--teal);}",
  ".workspace-tabs .navitem b{display: inline-block; background: rgb(237, 243, 242); color: rgb(80, 122, 118); font-size: 12px; margin-left: 0px; border-radius: 20px;}",
  ".demobar{background: rgb(247, 249, 248); padding: 8px 24px;}",
  ".workspace{position: relative;}",
  ".detail{position: absolute; right: 0px; top: 0px; bottom: 0px; width: min(390px, 100%); z-index: 15; background: white; box-shadow: -12px 0 35px #183f381c; padding: 24px;}",
  ".timegrid{min-width: 810px; grid-template-columns: 54px repeat(var(--cols),minmax(106px,1fr));}",
  ".timegrid.daygrid{min-width: 320px;}",
  ".sub,.filters select,.legend{font-size: 14px;}",
  ".ruler span,.eventmain small,.eventmeta{font-size: 12px;}",
  ".pagecontent{background: rgb(245, 247, 247); padding: 28px;}",
  ".card{border-radius: 18px; box-shadow: 0 3px 10px #26424105;}",
  ".cards{grid-template-columns: repeat(auto-fit,minmax(245px,1fr));}",
  ".views button.active{background: rgb(233, 242, 243); color: var(--teal);}",
  ".setup-card{margin-bottom: 22px;}",
  ".setup-card h3{margin-bottom: 12px;}",
  ".setup-card .setting:last-child{border: 0px;}",
  ".setup-card .setting small{font-size: 14px; line-height: 1.5;}",
  ".setup-card .badge{margin: 0px;}",
  ".sr-only{position: absolute; width: 1px; height: 1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px);}",
  "",
  "",
  "",
  ".booking-steps{display: flex; gap: 15px; margin-bottom: 24px; flex-wrap: wrap; font-size: 13px; color: rgb(138, 154, 156);}",
  ".booking-steps .current{font-weight: 750; color: var(--teal);}",
  ".booking-options{display: grid; gap: 12px;}",
  ".booking-options button{text-align: left; padding: 18px; border-radius: 16px;}",
  ".booking-options button strong{display: block; font-size: 17px; margin-bottom: 5px;}",
  ".booking-options button small{display: block; color: var(--muted); line-height: 1.5; font-size: 14px;}",
  ".booking-times{display: flex; gap: 10px; flex-wrap: wrap;}",
  ".booking-times button{padding: 12px 18px;}",
  ".dialogfoot button{border-radius: 22px;}",
  ".field:has([name=capacity])[hidden]{display: none;}",
  ".advanced-fields{margin-top: 18px; border-top: 1px solid var(--line); padding-top: 15px;}",
  ".advanced-fields summary{cursor: pointer; color: var(--teal); font-size: 14px; font-weight: 650; margin-bottom: 15px;}",
  "dialog{max-width: 700px;}",
  "",
  ".history-button{margin-left: auto; border: 0px; background: none; font-size: 13px; white-space: nowrap; color: var(--muted);}",
  ".history-button b{font-size: 12px; background: rgb(237, 243, 242); padding: 2px 6px; border-radius: 10px;}",
  ".setup-tabs{display: flex; gap: 8px; margin-bottom: 24px; flex-wrap: wrap;}",
  ".setup-tabs .active{background: rgb(233, 242, 243); color: var(--teal); border-color: var(--teal);}",
  ".day-header{border-radius: 0px; width: 100%; cursor: pointer; color: inherit;}",
  ".day-header:hover{background: rgb(231, 243, 243); color: var(--teal);}",
  ".day-header:focus-visible{outline-offset: -3px;}",
  ".day-tools{display: flex; gap: 8px; flex-wrap: wrap; margin: 18px 0px;}",
  ".day-tools select{max-width: 100%;}",
  ".day-sessions{max-height: 290px; overflow: auto; margin: 15px 0px; border-top: 1px solid var(--line); border-bottom: 1px solid var(--line);}",
  ".day-session{display: flex; gap: 12px; align-items: center; padding: 12px 4px; border-bottom: 1px solid var(--line); cursor: pointer;}",
  ".day-session:last-child{border: 0px;}",
  ".day-session input{width: 18px; height: 18px; accent-color: var(--teal); flex: 0 0 auto;}",
  ".day-session strong{font-size: 14px; display: block;}",
  ".day-session small{font-size: 13px; color: var(--muted); display: block; margin-top: 5px;}",
  ".day-session:has(input:checked){background: rgb(240, 247, 245);}",
  ".day-sessions p{font-size: 14px; line-height: 1.5;}",
  ".inline-coach{border: 1px solid transparent; background: transparent; color: var(--teal); font-weight: 700; padding: 4px 5px; max-width: 72%; font-size: 14px; cursor: pointer; text-align: right; margin: -4px -5px;}",
  ".inline-coach:hover,.inline-coach:focus{border-color: var(--line); background: rgb(240, 247, 245);}",
  ".eventmain{cursor: pointer;}",
  ".event.live-drag{z-index: 12; pointer-events: none; box-shadow: 0 8px 22px #163f3838; opacity: 0.94; will-change: top,height; outline: 2px solid var(--edge); transition: none;}",
  ".event.live-drag.invalid-drop{opacity: 0.45;}",
  ".event.pending-move{z-index: 12; outline: 2px solid var(--edge); box-shadow: 0 4px 16px #163f3825; pointer-events: none; transition: top 100ms ease-out,height 100ms ease-out;}",
  ".lane.dragover{background-color: rgb(237, 247, 244);}",
  ".dragging .calendar-scroll{scroll-behavior: auto;}",
  ".dragging .event{user-select: none;}",
  "@media (min-width:1600px) {",
  "",
  "}",
  "@media (max-width:1200px) {",
  ".headtools{gap: 6px;}",
  ".headtools button{font-size: 13px; padding: 9px 10px;}",
  ".workspace-tabs{gap: 18px;}",
  ".toolbar{gap: 10px;}",
  ".datecontrols h2{font-size: 16px;}",
  ".headtools #shareBooking{display: none;}}",
  "@media (max-width:900px) {body{padding: 8px; gap: 8px;}",
  "",
  "",
  "",
  "",
  "",
  "",
  "header{padding: 16px;}",
  ".headtools{max-width: 230px;}",
  ".workspace-tabs{padding: 0px 16px; gap: 16px;}",
  ".workspace-tabs .navitem{font-size: 13px;}",
  ".demobar{padding: 8px 16px;}",
  ".datecontrols{flex-wrap: wrap;}",
  ".toolbar{padding: 12px 16px;}}",
  "@media (max-width:700px) {body{padding: 0px;}",
  "main{border: 0px; border-radius: 0px;}",
  "",
  "",
  "",
  "",
  "",
  ".headtools{max-width: none;}",
  ".headtools #shareBooking{display: block;}",
  ".demobar span{font-size: 12px;}",
  ".detail{position: absolute; top: 0px; bottom: 0px; width: min(390px, 100%);}",
  ".workspace-tabs .navitem b{display: inline-block;}",
  ".pagecontent{padding: 18px;}",
  "",
  "",
  "header{gap: 10px;}",
  ".workspace-title{width: 100%;}",
  ".views button{font-size: 14px;}",
  ".legend{font-size: 12px;}",
  ".filters select{font-size: 14px;}",
  ".demobar{align-items: flex-start;}",
  ".booking-steps{gap: 10px;}}",
  "html,body{width:100%;height:100%;margin:0;padding:0;background:transparent}body{display:flex;gap:0}main{width:100%;min-width:0;border:0;border-radius:0;box-shadow:none}"
].join("\n");
const SCHEDULE_ENGINE = [
  "(function(root){",
  "  const DAY=86400000;",
  "  const date=s=>new Date(s+'T12:00:00Z');",
  "  const iso=d=>d.toISOString().slice(0,10);",
  "  const add=(s,n)=>iso(new Date(date(s).getTime()+n*DAY));",
  "  const diff=(a,b)=>Math.round((date(a)-date(b))/DAY);",
  "  const weekday=s=>date(s).getUTCDay();",
  "  const clone=x=>JSON.parse(JSON.stringify(x));",
  "  let seq=0;",
  "  const uid=()=> 'event-'+Date.now().toString(36)+'-'+(++seq);",
  "  function occurrences(state,from,to){",
  "    const out=[];",
  "    for(const rule of state.rules){",
  "      for(let d=from;d<=to;d=add(d,1)){",
  "        if(d<rule.date||d>(rule.until||'9999-12-31'))continue;",
  "        if(rule.repeat?weekday(d)!==weekday(rule.date):d!==rule.date)continue;",
  "        const key=rule.id+'@'+d;",
  "        if(state.exceptions[key])continue;",
  "        out.push({...clone(rule),key,ruleId:rule.id,originDate:d,date:d,roster:clone(state.rosters[key]||rule.roster||[])});",
  "      }",
  "    }",
  "    for(const [key,v] of Object.entries(state.exceptions)){",
  "      if(!v.deleted&&v.date>=from&&v.date<=to)out.push({...clone(v),key,roster:clone(state.rosters[key]||v.roster||[])});",
  "    }",
  "    return out.sort((a,b)=>a.date.localeCompare(b.date)||a.start-b.start);",
  "  }",
  "  function validate(e){",
  "    if(!e.title?.trim())throw Error('Add a title.');",
  "    if(!/^\\d{4}-\\d{2}-\\d{2}$/.test(e.date)||Number.isNaN(date(e.date).getTime()))throw Error('Choose a valid date.');",
  "    if(!Number.isInteger(e.start)||e.start<360||e.start>=1200||!Number.isInteger(e.duration)||e.duration<15||e.start+e.duration>1200)throw Error('Choose a session between 6 AM and 8 PM, at least 15 minutes long.');",
  "    if(e.until&&e.until<e.date)throw Error('End date must be on or after the first session.');",
  "    if(!Number.isInteger(e.capacity)||e.capacity<1||e.capacity>50)throw Error('Capacity must be 1–50.');",
  "    if(e.type==='one'&&e.capacity!==1)throw Error('A 1:1 session has one client.');",
  "    if(e.type==='room'&&!e.room)throw Error('Choose a room.');",
  "    if(e.type==='meeting'&&!e.staff?.length)throw Error('Choose at least one team member.');",
  "    if((e.type==='class'||e.type==='one')&&!e.coach)throw Error('Assign a coach.');",
  "    if((e.roster||[]).filter(x=>x.status!=='waitlist').length>e.capacity)throw Error('Capacity cannot be below the number booked.');",
  "  }",
  "  function resources(e){return [...new Set([e.coach,...(e.staff||[]),...(e.type==='block'?(e.staff||[]):[])].filter(Boolean))]}",
  "  function clashes(list){",
  "    const out=[];",
  "    for(let i=0;i<list.length;i++)for(let j=i+1;j<list.length;j++){",
  "      const a=list[i],b=list[j];if(a.date!==b.date||a.start>=b.start+b.duration||b.start>=a.start+a.duration)continue;",
  "      const reasons=[];const staff=resources(a).filter(x=>resources(b).includes(x));if(staff.length)reasons.push('staff: '+staff.join(', '));",
  "      if(a.room&&a.room===b.room)reasons.push('room: '+a.room);",
  "      const booked=e=>(e.roster||[]).filter(x=>x.status!=='waitlist').map(x=>x.member);",
  "      if(booked(a).some(x=>booked(b).includes(x)))reasons.push('client is already booked');",
  "      if(reasons.length)out.push({a:a.key,b:b.key,date:a.date,message:a.title+' / '+b.title+' — '+reasons.join('; ')});",
  "    }return out;",
  "  }",
  "  function stage(state,occ,patch,scope='single',deleting=false){",
  "    const next=clone(state);let focus=null;",
  "    if(!occ){const e={...patch,id:uid()};validate(e);next.rules.push(e);focus=e.id+'@'+e.date;return {state:next,focus};}",
  "    const rule=next.rules.find(r=>r.id===occ.ruleId);if(!rule)throw Error('Session no longer exists.');",
  "    if(scope==='single'||!rule.repeat){",
  "      if(deleting)next.exceptions[occ.key]={deleted:true};",
  "      else {const e={...occ,...patch,key:occ.key};validate(e);next.exceptions[occ.key]=e;focus=occ.key;}",
  "    }else{",
  "      const shift=patch.date?diff(patch.date,occ.date):0;",
  "      const oldUntil=rule.until;",
  "      if(scope==='future')rule.until=add(occ.originDate,-1);",
  "      else next.rules=next.rules.filter(r=>r.id!==rule.id);",
  "      let replacement;",
  "      if(!deleting){",
  "        replacement={...rule,...patch,id:uid(),date:add(scope==='future'?occ.originDate:rule.date,shift),until:patch.until??oldUntil,roster:clone(rule.roster||[])};",
  "        validate(replacement);next.rules.push(replacement);focus=replacement.id+'@'+add(occ.originDate,shift);",
  "      }",
  "      for(const key of new Set([...Object.keys(next.exceptions),...Object.keys(next.rosters)])){",
  "        if(!key.startsWith(rule.id+'@'))continue;const d=key.split('@')[1];if(scope==='future'&&d<occ.originDate)continue;",
  "        if(replacement){const nk=replacement.id+'@'+add(d,shift);if(next.rosters[key])next.rosters[nk]=next.rosters[key];if(next.exceptions[key]?.deleted)next.exceptions[nk]={deleted:true};}",
  "        delete next.exceptions[key];delete next.rosters[key];",
  "      }",
  "    }",
  "    return {state:next,focus};",
  "  }",
  "  function newConflicts(before,after,from,to){",
  "    const old=clashes(occurrences(before,from,to));",
  "    const seen=new Set(old.map(x=>x.date+'|'+x.message));",
  "    return clashes(occurrences(after,from,to)).filter(x=>!seen.has(x.date+'|'+x.message));",
  "  }",
  "  const api={date,iso,add,diff,weekday,clone,uid,occurrences,validate,resources,clashes,stage,newConflicts};",
  "  root.ScheduleEngine=api;if(typeof module!=='undefined')module.exports=api;",
  "})(typeof window==='undefined'?globalThis:window);",
  ""
].join("\n");
const SCHEDULE_APP = [
  "'use strict';",
  "(()=>{",
  "const E=ScheduleEngine,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];",
  "const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;'}[c]));",
  "const types={class:'Class / semi-private',one:'1:1 session',room:'Room booking',meeting:'Team meeting',block:'Blocked time'};",
  "const palette={class:['#dff3e9','#159175','#174d3c'],one:['#e7f0ff','#437fd0','#24518a'],room:['#f0eaff','#8961c6','#604087'],meeting:['#fff0d9','#c88a2b','#7c551c'],block:['#edf0f2','#819199','#445b64']};",
  "const coaches=['Hayden Guzinski','Rolland Cheng','Alex Morgan','Shani Naughton'];",
  "const rooms=['Studio A','PT suite','Recovery room','Meeting room'];",
  "const clients=[{name:'Jordan Miller',credits:8},{name:'Alicia King',credits:3},{name:'Taylor Smith',credits:0},{name:'Brandon Lee',credits:5},{name:'Morgan Davis',credits:10},{name:'Casey Wilson',credits:6}];",
  "const localToday=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};",
  "const base=E.add(localToday(),-((E.weekday(localToday())+6)%7));",
  "let state,services,settings,availability,activity=[],view='week',anchor=base,page='calendar',selected=null,visible=[],all=[],submitAction=null,drag=null,pendingDrag=null;",
  "const time=n=>`${(Math.floor(n/60)%12)||12}:${String(n%60).padStart(2,'0')} ${n>=720?'PM':'AM'}`;",
  "const timeInput=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;",
  "const minutes=t=>{const [h,m]=t.split(':').map(Number);return h*60+m};",
  "const label=(s,opts={month:'short',day:'numeric'})=>E.date(s).toLocaleDateString('en-US',{...opts,timeZone:'UTC'});",
  "const weekStart=s=>E.add(s,-((E.weekday(s)+6)%7));",
  "const isMember=()=>$('#audience').value==='member';",
  "const chosenMember=()=>$('#member').value;",
  "const booked=e=>(e.roster||[]).filter(r=>r.status!=='waitlist');",
  "const memberClients=e=>booked(e).map(r=>r.member);",
  "const initials=s=>s.split(' ').map(x=>x[0]).slice(0,2).join('');",
  "const option=(v,text,sel)=>`<option value=\"${esc(v)}\" ${v===sel?'selected':''}>${esc(text??v)}</option>`;",
  "function seed(){",
  " state={rules:[],exceptions:{},rosters:{}};activity=[];",
  " services=[{id:'sg',name:'Small Group Training',type:'class',duration:45,capacity:6,price:35,cancel:12},{id:'pt',name:'Personal Training',type:'one',duration:60,capacity:1,price:75,cancel:24},{id:'rc',name:'Recovery Consultation',type:'one',duration:30,capacity:1,price:45,cancel:2}];",
  " settings={waitlist:true,notify:true,zero:true,mobile:true,public:true};",
  " availability=Object.fromEntries(coaches.map(c=>[c,{start:360,end:1200}]));",
  " const rule=(date,start,type,title,coach,room,duration=45,count=0,repeat=false,staff=[])=>{const r={id:E.uid(),date,start,type,title,coach,room,duration,capacity:type==='class'?6:1,repeat,until:'',staff,notes:'',service:type==='class'?'sg':type==='one'?'pt':'',visibility:type==='class'||type==='one'?'members':'internal',roster:Array.from({length:count},(_,i)=>({member:clients[i%clients.length].name,status:'booked'}))};state.rules.push(r);return r;};",
  " for(let d=0;d<5;d++){",
  "  const date=E.add(base,d);",
  "  for(const [i,t] of [360,420,480,660].entries())rule(date,t,'class','Small Group Training',i<2?coaches[0]:i===2?coaches[1]:coaches[2],'Studio A',45,(d===3&&i===0)?0:((d+i)%4)+2,true);",
  "  if(d<4)for(const t of [960,1005,1050,1095])rule(date,t,'class','Small Group Training',d===2?coaches[1]:coaches[3],'Studio A',45,(d+t/15)%4+1,true);",
  " }",
  " rule(base,570,'one','Personal Training',coaches[0],'PT suite',60,1,true);",
  " rule(E.add(base,1),555,'one','Personal Training',coaches[2],'PT suite',60,1,true).roster=[{member:'Alicia King',status:'booked'}];",
  " rule(E.add(base,2),540,'one','Personal Training',coaches[0],'PT suite',60,1,true).roster=[{member:'Brandon Lee',status:'booked'}];",
  " rule(E.add(base,3),570,'one','Recovery Consultation',coaches[2],'Recovery room',30,1,true).service='rc';",
  " rule(E.add(base,4),555,'one','Personal Training',coaches[1],'PT suite',60,0,true);",
  " rule(base,735,'room','Recovery • Jordan','', 'Recovery room',45,0,false).notes='Booked by Jordan Miller. Compression and mobility.';",
  " rule(E.add(base,2),765,'room','Independent recovery','', 'Recovery room',60,0,true).notes='Booked by Alicia King';",
  " rule(E.add(base,1),810,'meeting','Weekly team huddle','', 'Meeting room',45,0,true,coaches);",
  " rule(E.add(base,4),840,'meeting','Programming review','', 'Meeting room',45,0,true,[coaches[1],coaches[2]]);",
  " rule(E.add(base,3),735,'block','Room maintenance','', 'PT suite',75,0,false);",
  " rule(E.add(base,2),720,'block','Alex • lunch',coaches[2],'',45,0,true);",
  " rule(E.add(base,5),540,'room','Studio rental','', 'Studio A',90,0,false).notes='Private rental. Owner: Morgan Davis.';",
  " selected=null;view='week';anchor=localToday();page='calendar';",
  "}",
  "function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}",
  "function log(title,detail){activity.unshift({title,detail,at:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})});$('#activityCount').textContent=activity.length}",
  "function range(){if(view==='month'){const first=anchor.slice(0,7)+'-01';const start=weekStart(first);return[start,E.add(start,41)]}if(['day','coaches','rooms'].includes(view))return[anchor,anchor];const start=weekStart(anchor);return[start,E.add(start,6)]}",
  "function colors(e){if($('#colorBy').value==='coach'&&e.coach)return Object.values(palette)[coaches.indexOf(e.coach)%4];return palette[e.type]}",
  "function style(e){const [a,b,c]=colors(e);return `--tint:${a};--edge:${b};--text:${c}`}",
  "function populateFilters(){",
  " $('#typeFilter').innerHTML=option('all','All booking types')+Object.entries(types).map(([k,v])=>option(k,v)).join('');",
  " $('#coachFilter').innerHTML=option('all','All coaches')+coaches.map(x=>option(x)).join('');",
  " $('#roomFilter').innerHTML=option('all','All rooms')+rooms.map(x=>option(x)).join('');",
  " $('#member').innerHTML=clients.map(x=>option(x.name,x.name)).join('');",
  "}",
  "function filter(e){if(isMember()&&(!['class','one'].includes(e.type)||e.visibility==='internal'))return false;return ($('#typeFilter').value==='all'||e.type===$('#typeFilter').value)&&($('#coachFilter').value==='all'||E.resources(e).includes($('#coachFilter').value))&&($('#roomFilter').value==='all'||e.room===$('#roomFilter').value)}",
  "function render(){",
  " ",
  " $('#activityCount').textContent=activity.length;",
  " $$('.navitem').forEach(b=>b.classList.toggle('active',b.dataset.page===page||(b.dataset.page==='settings'&&page==='staff')));",
  " $('#calendarPage').classList.toggle('hidden',page!=='calendar');$('#otherPage').classList.toggle('hidden',page==='calendar');",
  " $('#newEvent').classList.toggle('hidden',isMember());$('#member').classList.toggle('hidden',!isMember());",
  " $$('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);b.disabled=isMember()&&['coaches','rooms'].includes(b.dataset.view)});",
  " $('#legend').innerHTML=Object.entries(types).filter(([k])=>!isMember()||['class','one'].includes(k)).map(([k,v])=>`<span><i class=\"swatch\" style=\"background:${palette[k][1]}\"></i>${esc(v)}</span>`).join('');",
  " if(page!=='calendar'){renderPage();enhanceSetup();return}",
  " const [from,to]=range();all=E.occurrences(state,from,to);visible=all.filter(filter);",
  " $('#dateLabel').textContent=view==='month'?label(anchor,{month:'long',year:'numeric'}):from===to?label(from,{weekday:'short',month:'short',day:'numeric'}):`${label(from)}–${label(to,{day:'numeric'})}, ${from.slice(0,4)}`;",
  " $('#summary').textContent=`${visible.length} bookings · ${visible.filter(x=>['class','one'].includes(x.type)&&!booked(x).length).length} empty sessions`;",
  " if(view==='month'){renderMonth(from,to);if(!isMember())$$('[data-day]').forEach(b=>b.onclick=()=>manageDay(b.dataset.day))}else renderGrid(from,to);",
  " renderDetail();",
  "}",
  "function lanesFor(from,to){if(view==='coaches')return coaches.map(c=>({title:c.split(' ')[0],sub:c.split(' ').slice(1).join(' '),date:anchor,coach:c,events:visible.filter(e=>E.resources(e).includes(c))}));if(view==='rooms')return rooms.map(r=>({title:r,sub:'Room availability',date:anchor,room:r,events:visible.filter(e=>e.room===r)}));let lanes=[];for(let d=from;d<=to;d=E.add(d,1))lanes.push({title:label(d,{weekday:'short',day:'numeric'}),sub:label(d,{month:'short'}),date:d,events:visible.filter(e=>e.date===d)});return lanes;}",
  "function positions(events){const arr=events.slice().sort((a,b)=>a.start-b.start||b.duration-a.duration);const result=new Map();let group=[],end=-1;function assign(){let ends=[];for(const e of group){let col=ends.findIndex(x=>x<=e.start);if(col<0)col=ends.length;ends[col]=e.start+e.duration;result.set(e.key,{col,n:0})}for(const e of group)result.get(e.key).n=ends.length;}for(const e of arr){if(e.start>=end&&group.length){assign();group=[];end=-1}group.push(e);end=Math.max(end,e.start+e.duration)}assign();return result}",
  "function renderGrid(from,to){const lanes=lanesFor(from,to);const grid=$('#calendar');grid.className='timegrid '+(lanes.length===1?'daygrid':'');grid.style.setProperty('--cols',lanes.length);grid.innerHTML=`<div class=\"gridhead\"><small>Local<br>time</small></div>`+lanes.map(l=>`<div class=\"gridhead ${l.date===anchor?'focusday':''}\">${esc(l.title)}<small>${esc(l.sub)}</small></div>`).join('')+`<div class=\"ruler\">${Array.from({length:14},(_,i)=>`<span style=\"top:${i*72}px\">${time((i+6)*60).replace(':00','')}</span>`).join('')}</div>`+lanes.map((l,i)=>{const pos=positions(l.events);return `<div class=\"lane\" data-lane=\"${i}\" data-date=\"${l.date}\" data-coach=\"${esc(l.coach||'')}\" data-room=\"${esc(l.room||'')}\">${l.events.map(e=>{const {col,n}=pos.get(e.key);const roster=booked(e);const title=isMember()&&e.type==='one'?(roster.length?'Reserved 1:1':e.title):e.title;const person=!isMember()&&e.type==='one'&&roster.length?roster[0].member:e.coach?.split(' ')[0]||e.room;return `<article class=\"event ${e.key===selected?'selected':''} ${['class','one'].includes(e.type)&&!roster.length?'zero':''}\" data-key=\"${esc(e.key)}\" style=\"${style(e)};top:${(e.start-360)*1.2+2}px;height:${e.duration*1.2-4}px;left:calc(${col/n*100}% + 3px);width:calc(${100/n}% - 6px)\"><button class=\"eventmain\" data-open=\"${esc(e.key)}\" title=\"${esc(title)} · ${time(e.start)}–${time(e.start+e.duration)}\"><small>${time(e.start)}${n===1?' · '+(e.type==='class'?'Class':e.type==='one'?'1:1':e.type==='room'?'Room':e.type==='meeting'?'Team':'Blocked'):''}</small><strong>${esc(title)}</strong><span class=\"eventmeta\"><span>${esc(person||'Internal')}</span><span>${['class','one'].includes(e.type)?roster.length+'/'+e.capacity:''}</span></span></button>${!isMember()?`<button class=\"grip\" aria-label=\"Drag to move ${esc(e.title)}\" title=\"Drag to move\">⠿</button><button class=\"resize\" aria-label=\"Drag to resize ${esc(e.title)}\" title=\"Drag to change duration\"></button>`:''}</article>`}).join('')}</div>`}).join('');",
  " $$('.eventmain').forEach(b=>b.onclick=()=>{if(Date.now()<(window.suppressClickUntil||0))return;selected=b.dataset.open;render()});",
  " $$('.lane').forEach(l=>l.addEventListener('click',e=>{if(e.target!==l||isMember()||Date.now()<(window.suppressClickUntil||0))return;const start=Math.min(1185,Math.max(360,360+Math.floor((e.clientY-l.getBoundingClientRect().top)/18)*15));editBooking(null,{date:l.dataset.date,start,coach:l.dataset.coach||coaches[0],room:l.dataset.room||'',type:view==='rooms'?'room':'class'})}));",
  " $$('.event').forEach(el=>el.addEventListener('pointerdown',startDrag));",
  " if(['day','week'].includes(view))$$('#calendar > .gridhead').slice(1).forEach((head,i)=>{const b=document.createElement('button');b.className=head.className+' day-header';b.innerHTML=head.innerHTML;b.dataset.scheduleDay=lanes[i].date;b.setAttribute('aria-label',label(lanes[i].date,{weekday:'long',month:'long',day:'numeric'})+(isMember()?' — open day':' — manage sessions and coaches'));b.title=isMember()?'Open day':'Click to manage this day’s coaches';b.onclick=()=>{if(isMember()){anchor=lanes[i].date;view='day';selected=null;render()}else manageDay(lanes[i].date)};head.replaceWith(b)});",
  "}",
  "function renderMonth(from,to){const grid=$('#calendar');grid.className='monthgrid';grid.style.removeProperty('--cols');grid.innerHTML=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(x=>`<div class=\"gridhead\">${x}</div>`).join('');for(let d=from;d<=to;d=E.add(d,1)){const events=visible.filter(x=>x.date===d);grid.insertAdjacentHTML('beforeend',`<div class=\"monthcell ${d.slice(0,7)!==anchor.slice(0,7)?'off':''}\"><button data-day=\"${d}\" title=\"Open day\">${Number(d.slice(-2))}</button>${events.slice(0,4).map(e=>`<button class=\"monthEvent\" data-month-open=\"${esc(e.key)}\" style=\"${style(e)}\">${time(e.start)} ${esc(isMember()&&e.type==='one'&&booked(e).length?'Reserved 1:1':e.title)}</button>`).join('')}${events.length>4?`<button data-day=\"${d}\">+${events.length-4} more</button>`:''}</div>`)}$$('[data-day]').forEach(b=>b.onclick=()=>{anchor=b.dataset.day;view='day';render()});$$('[data-month-open]').forEach(b=>b.onclick=()=>{selected=b.dataset.monthOpen;renderDetail()})}",
  "function manageDay(date){",
  " const sessions=E.occurrences(state,date,date).filter(e=>['class','one'].includes(e.type));",
  " openDialog(label(date,{weekday:'long',month:'short',day:'numeric'}),`<p class=\"sub\">Select sessions to cover, then choose a replacement coach. Includes all classes and 1:1s on this day, regardless of calendar filters.</p><div class=\"day-tools\"><select id=\"dayCoach\" aria-label=\"Current coach\">${option('all','All coaches')+coaches.map(c=>option(c)).join('')}</select><button type=\"button\" data-select-block=\"all\">All day</button><button type=\"button\" data-select-block=\"morning\">Morning</button><button type=\"button\" data-select-block=\"afternoon\">Afternoon</button><button type=\"button\" data-select-block=\"none\">Clear</button><button type=\"button\" id=\"openDayView\">Open day view</button></div><div class=\"day-sessions\">${sessions.map(e=>`<label class=\"day-session\"><input type=\"checkbox\" name=\"daySession\" value=\"${esc(e.key)}\" checked><span><strong>${time(e.start)} · ${esc(e.title)}</strong><small>${esc(e.coach)} · ${esc(e.room)} · ${booked(e).length}/${e.capacity} booked</small></span></label>`).join('')||'<p>No classes or 1:1s scheduled. Open day view to add a booking.</p>'}</div><p id=\"daySelection\" class=\"sub\"></p>${field('replacement','Replacement coach',`<select required><option value=\"\">Choose coach…</option>${coaches.map(c=>option(c)).join('')}</select>`)}<div class=\"scope\"><strong>Apply to</strong><label><input type=\"radio\" name=\"dayScope\" value=\"single\" checked>Only the selected sessions on this day</label><label><input type=\"radio\" name=\"dayScope\" value=\"future\">Selected sessions and their future weekly occurrences</label></div>${notifyHTML()}`,()=>{",
  " const keys=new Set($$('[name=daySession]:checked').map(x=>x.value)),picked=sessions.filter(e=>keys.has(e.key));const coach=$('#editor').elements.replacement.value,scope=$('#editor').elements.dayScope.value,notify=$('#editor').elements.notify.checked;",
  " if(!picked.length)throw Error('Select at least one session.');if(!coaches.includes(coach))throw Error('Choose a replacement coach.');const changed=picked.filter(e=>e.coach!==coach);if(!changed.length)throw Error('That coach already owns every selected session.');",
  " const affected=scope==='single'?changed:E.occurrences(state,date,E.add(date,364)).filter(e=>changed.some(c=>c.ruleId===e.ruleId&&e.originDate>=c.originDate));const recipients=[...new Set(affected.flatMap(e=>[...E.resources(e),...memberClients(e)]).concat(coach))];",
  " openDialog('Review coach change',`<div class=\"note\"><strong>${changed.length} session${changed.length===1?'':'s'} → ${esc(coach)}</strong><br>${label(date,{weekday:'long',month:'long',day:'numeric'})}<br>${scope==='single'?'This day only':'These sessions and their future weekly occurrences'}</div><div class=\"day-sessions\">${changed.map(e=>`<p><strong>${time(e.start)} · ${esc(e.title)}</strong><br><small>${esc(e.coach)} → ${esc(coach)}</small></p>`).join('')}</div><p class=\"sub\">${notify?'Notification preview: '+esc(recipients.join(', '))+'. Nothing will be sent.':'No notification preview requested.'}</p><p class=\"sub\">Coach, room and member conflicts are checked before saving. Recurring checks and recipient previews cover the next 52 weeks. If a conflict is found, none of these changes are saved.</p>`,()=>{",
  " let next=state;const handled=new Set();for(const e of changed){if(scope==='future'&&handled.has(e.ruleId))continue;next=E.stage(next,e,{coach},scope).state;handled.add(e.ruleId)}",
  " checkAndApply(next,null,date,'Coaches updated',changed.length+' sessions · '+coach+' · '+scope);if(notify)log('Notification preview — nothing sent','Coach changed to '+coach+'. Recipients: '+recipients.join(', '));anchor=date;selected=null;render();",
  " },'Confirm coach change');",
  " },'Review coach change');",
  " const update=()=>{$('#daySelection').textContent=$$('[name=daySession]:checked').length+' sessions selected'};",
  " const selectBlock=block=>{const c=$('#dayCoach').value;$$('[name=daySession]').forEach(input=>{const e=sessions.find(s=>s.key===input.value);input.checked=(c==='all'||e.coach===c)&&(block==='all'||block==='morning'&&e.start<720||block==='afternoon'&&e.start>=720)});update()};",
  " $$('[data-select-block]').forEach(b=>b.onclick=()=>selectBlock(b.dataset.selectBlock));$('#dayCoach').onchange=()=>selectBlock('all');$$('[name=daySession]').forEach(x=>x.onchange=update);$('#openDayView').onclick=()=>{closeDialog();anchor=date;view='day';selected=null;render()};update();",
  "}",
  "function current(){return all.find(e=>e.key===selected)||null}",
  "function renderDetail(){const pane=$('#detail'),e=current();pane.classList.toggle('hidden',!e);if(!e)return;const roster=booked(e),waiting=e.roster.filter(x=>x.status==='waitlist');const privateOne=isMember()&&e.type==='one'&&roster.length&&!memberClients(e).includes(chosenMember());",
  " pane.innerHTML=`<button class=\"close\" aria-label=\"Close details\">×</button><span class=\"eyebrow\">${esc(types[e.type])}</span><h2>${esc(privateOne?'Reserved 1:1':e.title)}</h2><p class=\"sub\">${label(e.date,{weekday:'long',month:'short',day:'numeric'})}<br>${time(e.start)}–${time(e.start+e.duration)} · ${e.duration} min</p><span class=\"badge\">${e.repeat?'Repeats weekly':'One-time booking'}</span><div class=\"kv\"><span>Coach / staff</span><b>${esc(e.coach||e.staff.join(', ')||'—')}</b></div><div class=\"kv\"><span>Room</span><b>${esc(e.room||'No room reserved')}</b></div>${!isMember()?`<div class=\"kv\"><span>Visibility</span><b>${e.visibility==='members'?'Bookable by members':'Staff only'}</b></div>`:''}",
  " ${['class','one'].includes(e.type)?`<div class=\"section\"><div class=\"kv\"><span>Booked / capacity</span><b>${roster.length} / ${e.capacity}</b></div><div class=\"progress\"><span style=\"width:${roster.length/e.capacity*100}%\"></span></div>${!isMember()?`<div class=\"roster\">${e.roster.map(r=>rosterMarkup(r,e)).join('')||'<p class=\"sub\">No members booked yet.</p>'}</div><button id=\"addMember\" class=\"primary\" style=\"width:100%;margin-top:10px\">＋ Add member / waitlist</button>`:`<div class=\"note\">${esc(chosenMember())} · ${creditBalance(chosenMember())} credits remaining</div><button class=\"primary\" id=\"memberBook\" ${privateOne?'disabled':''} style=\"width:100%;margin-top:10px\">${e.roster.some(x=>x.member===chosenMember())?'Cancel my booking':roster.length>=e.capacity?'Join waitlist':'Book this session'}</button>`}${waiting.length?`<p class=\"sub\">${waiting.length} on waitlist</p>`:''}${!roster.length&&!isMember()&&settings.zero?'<div class=\"note alert\" style=\"margin-top:12px\">Empty session. Use “Simulate alert” to preview the coach reminder.</div><button id=\"zeroAlert\" style=\"margin-top:8px\">Simulate alert</button>':''}</div>`:''}",
  " ${e.notes&&!isMember()?`<div class=\"section\"><h3>Notes</h3><p class=\"sub\">${esc(e.notes)}</p></div>`:''}",
  " ${!isMember()?'<div class=\"section\"><div class=\"buttons\"><button id=\"edit\">Edit</button><button id=\"duplicate\">Duplicate</button></div><div class=\"buttons\"><button id=\"message\">Draft message</button><button class=\"danger\" id=\"delete\">Delete</button></div></div>':''}`;",
  " pane.querySelector('.close').onclick=()=>{selected=null;render()};",
  " if(!isMember()&&['class','one'].includes(e.type)){",
  "  const coachSelect=document.createElement('select');coachSelect.id='bookingCoach';coachSelect.className='inline-coach';coachSelect.setAttribute('aria-label','Coach for this session');coachSelect.innerHTML=coaches.map(c=>option(c,c,e.coach)).join('');coachSelect.onchange=()=>{const coach=coachSelect.value;coachSelect.value=e.coach;if(coach!==e.coach)confirmChange(e,{coach})};pane.querySelector('.kv b').replaceWith(coachSelect);",
  " }",
  " if(isMember()){$('#memberBook')?.addEventListener('click',()=>{if(e.roster.some(x=>x.member===chosenMember()))removeMember(e,chosenMember());else addMember(e,chosenMember());});return}",
  " $('#edit').onclick=()=>editBooking(e);$('#duplicate').onclick=()=>editBooking(null,{...e,id:undefined,date:E.add(e.date,1),repeat:false,roster:[]});$('#delete').onclick=()=>confirmChange(e,{},true);$('#message').onclick=()=>draftMessage(e);",
  " $('#addMember')?.addEventListener('click',()=>chooseMember(e));$('#zeroAlert')?.addEventListener('click',()=>{log('Simulated zero-booking alert',`${e.coach}: ${e.title}, ${label(e.date)} at ${time(e.start)} has no bookings. Nothing sent.`);toast('Alert preview recorded in Activity. Nothing sent.');});",
  " $$('[data-remove]').forEach(b=>b.onclick=()=>removeMember(e,b.dataset.remove));$$('[data-attend]').forEach(s=>s.onchange=()=>setAttendance(e,s.dataset.attend,s.value));$$('[data-promote]').forEach(b=>b.onclick=()=>promote(e,b.dataset.promote));",
  "}",
  "function rosterMarkup(r,e){return `<div class=\"rosteritem\"><span class=\"avatar\">${initials(r.member)}</span><div class=\"persontext\">${esc(r.member)}<small>${creditBalance(r.member)} credits${r.status==='waitlist'?' · Waitlisted':''}</small></div>${r.status==='waitlist'?`<button data-promote=\"${esc(r.member)}\" title=\"Promote from waitlist\">↑</button>`:`<select data-attend=\"${esc(r.member)}\" aria-label=\"Attendance for ${esc(r.member)}\">${['booked','attended','no-show'].map(v=>option(v,v==='no-show'?'No-show':v[0].toUpperCase()+v.slice(1),r.status)).join('')}</select>`}<button data-remove=\"${esc(r.member)}\" aria-label=\"Remove ${esc(r.member)}\">×</button></div>`}",
  "function creditBalance(member){let used=0;for(const list of Object.values(state.rosters))used+=list.filter(r=>r.member===member&&r.status==='attended').length;return (clients.find(c=>c.name===member)?.credits||0)-used}",
  "function updateRoster(e,list){state.rosters[e.key]=E.clone(list);render()}",
  "function overlapsMember(e,name){return E.occurrences(state,e.date,e.date).some(x=>x.key!==e.key&&x.start<e.start+e.duration&&e.start<x.start+x.duration&&memberClients(x).includes(name))}",
  "function addMember(e,name){if(e.roster.some(x=>x.member===name)){toast('Already on this roster.');return false}if(creditBalance(name)<=0){toast('No eligible credits. Add a package before booking.');return false}const full=booked(e).length>=e.capacity;if(full&&!settings.waitlist){toast('This session is full and waitlisting is off.');return false}if(!full&&overlapsMember(e,name)){toast('Conflict: this member is already booked at this time.');return false}updateRoster(e,[...e.roster,{member:name,status:full?'waitlist':'booked'}]);log(full?'Member waitlisted':'Member booked',name+' · '+e.title+' · '+label(e.date));toast(full?'Added to waitlist.':'Member added. Credit is used at check-in.');return true}",
  "function removeMember(e,name){let list=e.roster.filter(x=>x.member!==name);const free=e.roster.find(x=>x.member===name)?.status!=='waitlist';if(free&&settings.waitlist){const next=list.find(r=>r.status==='waitlist'&&creditBalance(r.member)>0&&!overlapsMember(e,r.member));if(next){next.status='booked';log('Waitlist promotion',next.member+' moved into '+e.title)}}updateRoster(e,list);log('Booking removed',name+' · '+e.title);toast('Removed. Attendance credit restored if applicable.')}",
  "function promote(e,name){if(booked(e).length>=e.capacity){toast('No open spots.');return}if(creditBalance(name)<=0||overlapsMember(e,name)){toast('Cannot promote: check member credits or schedule conflict.');return}updateRoster(e,e.roster.map(r=>r.member===name?{...r,status:'booked'}:r));log('Waitlist promotion',name+' · '+e.title);toast('Member promoted.')}",
  "function setAttendance(e,name,status){const old=e.roster.find(r=>r.member===name);if(status==='attended'&&old.status!=='attended'&&creditBalance(name)<=0){toast('No credit available for check-in.');render();return}updateRoster(e,e.roster.map(r=>r.member===name?{...r,status}:r));log('Attendance updated',name+' · '+status+' · '+e.title);toast(status==='attended'?'Checked in. One demo credit used.':'Attendance updated. No-show does not use a demo credit.')}",
  "function openDialog(title,body,action,submit='Save'){const d=$('#dialog');$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;$('#formError').textContent='';$('#confirmDialog').textContent=submit;submitAction=action;if(!d.open)d.showModal();}",
  "function closeDialog(){$('#dialog').close();submitAction=null;if(pendingDrag){pendingDrag=null;render()}}",
  "function field(name,labelText,html,full=false){return `<label class=\"field ${full?'full':''}\">${labelText}${html.replace('<input',`<input name=\"${name}\"`).replace('<select',`<select name=\"${name}\"`).replace('<textarea',`<textarea name=\"${name}\"`)}</label>`}",
  "function chooseMember(e){openDialog('Add a member',`<p class=\"sub\">Credits are checked on booking. Full classes use the waitlist.</p>${field('member','Member',`<select>${clients.filter(c=>!e.roster.some(r=>r.member===c.name)).map(c=>option(c.name,c.name+' · '+creditBalance(c.name)+' credits')).join('')}</select>`)}`,()=>{const name=$('#editor').elements.member.value;if(name&&addMember(e,name))closeDialog()},'Add member')}",
  "function scopeHTML(e){return e.repeat?`<div class=\"scope\"><strong>Apply to</strong>${[['single','Only this session'],['future','This and future sessions'],['series','Every session in this series']].map(([v,t],i)=>`<label><input type=\"radio\" name=\"scope\" value=\"${v}\" ${!i?'checked':''}>${t}</label>`).join('')}</div>`:''}",
  "function notifyHTML(){return `<label class=\"check\"><input name=\"notify\" type=\"checkbox\" ${settings.notify?'checked':''}>Preview notifications to affected members and staff</label><p class=\"sub\">Nothing is sent. The recipient list is saved in Activity.</p>`}",
  "function editBooking(e=null,preset={}){",
  " const s={type:'class',title:'Small Group Training',service:'sg',date:anchor,start:540,duration:45,coach:coaches[0],room:'Studio A',capacity:6,repeat:false,until:'',notes:'',staff:[],visibility:'members',roster:[],...E.clone(e||{}),...preset};",
  " const body=`<div class=\"formgrid\">${field('type','Booking type',`<select id=\"editType\">${Object.entries(types).map(([k,v])=>option(k,v,s.type)).join('')}</select>`)}${field('service','Service template',`<select id=\"editService\">${option('','Custom / no service')+services.map(v=>option(v.id,v.name,s.service)).join('')}</select>`)}${field('title','Title',`<input required maxlength=\"80\" value=\"${esc(s.title)}\">`,true)}${field('date','Date',`<input required type=\"date\" value=\"${s.date}\">`)}${field('start','Start time',`<input required type=\"time\" step=\"900\" value=\"${timeInput(s.start)}\">`)}${field('duration','Duration (minutes)',`<input required type=\"number\" min=\"15\" max=\"840\" step=\"15\" value=\"${s.duration}\">`)}${field('capacity','Capacity',`<input required type=\"number\" min=\"1\" max=\"50\" value=\"${s.capacity}\">`)}${field('coach','Coach / staff owner',`<select>${option('','Unassigned')+coaches.map(c=>option(c,c,s.coach)).join('')}</select>`)}${field('room','Reserve room',`<select>${option('','No room')+rooms.map(r=>option(r,r,s.room)).join('')}</select>`)}<div class=\"field full\" id=\"staffField\"><span>Team attendees</span><div class=\"checkgroup\">${coaches.map(c=>`<label class=\"check\"><input name=\"staff\" type=\"checkbox\" value=\"${esc(c)}\" ${s.staff.includes(c)?'checked':''}>${esc(c.split(' ')[0])}</label>`).join('')}</div></div>${!e?field('repeat','Repeat',`<select>${option('none','One time',s.repeat?'weekly':'none')+option('weekly','Weekly',s.repeat?'weekly':'none')}</select>`):'<p class=\"sub\">'+(s.repeat?'Weekly series. Choose the edit scope below.':'One-time booking.')+'</p>'}${field('until','Repeat end (optional)',`<input type=\"date\" value=\"${s.until||''}\">`)}${!e?`<div class=\"field full\" id=\"weekdaysField\"><span>Repeat on (weekly only)</span><div class=\"checkgroup\">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=>`<label class=\"check\"><input type=\"checkbox\" name=\"weekdays\" value=\"${(i+1)%7}\" ${(i+1)%7===E.weekday(s.date)?'checked':''}>${d}</label>`).join('')}</div>`:''}${field('visibility','Visibility',`<select>${option('members','Bookable by members',s.visibility)+option('internal','Staff only',s.visibility)}</select>`)}${field('notes','Notes / room booking owner / meeting link',`<textarea maxlength=\"1000\">${esc(s.notes)}</textarea>`,true)}</div>${e?scopeHTML(e)+notifyHTML():''}<p class=\"sub\">Recurring conflict checks cover the next 52 weeks from the change. Room reservations are exclusive; staff blocks also prevent double-booking.</p>`;",
  " openDialog(e?'Edit booking':'New booking',body,()=>{",
  "  const f=$('#editor'),val=n=>f.elements[n]?.value;",
  "  const patch={type:val('type'),title:val('title').trim(),service:val('service'),date:val('date'),start:minutes(val('start')),duration:Number(val('duration')),capacity:Number(val('capacity')),coach:val('coach'),room:val('room'),staff:[...f.querySelectorAll('[name=staff]:checked')].map(x=>x.value),repeat:e?s.repeat:val('repeat')==='weekly',until:val('until'),visibility:val('visibility'),notes:val('notes'),roster:e?e.roster:[]};",
  "  if(!['class','one'].includes(patch.type))patch.visibility='internal';if(patch.type==='one')patch.capacity=1;",
  "  if(e){if(!['class','one'].includes(patch.type)&&e.roster.length)throw Error('Remove the member roster before changing to an internal booking.');commit(e,patch,val('scope')||'single',false,f.elements.notify?.checked);}",
  "  else{",
  "   let next=state,focus=null;let dates=[patch.date];if(patch.repeat){const days=[...f.querySelectorAll('[name=weekdays]:checked')].map(x=>Number(x.value));if(!days.length)throw Error('Choose at least one repeat day.');dates=days.map(d=>E.add(patch.date,(d-E.weekday(patch.date)+7)%7));}",
  "   for(const d of dates){const result=E.stage(next,null,{...patch,date:d});next=result.state;focus=focus||result.focus;}",
  "   checkAndApply(next,focus,patch.date,'Booking created',patch.title+' · '+dates.length+' weekly pattern(s)');",
  "  }",
  " },e?'Save changes':'Create booking');",
  " function typeFields(){const t=$('#editType').value;$('#staffField').classList.toggle('hidden',t!=='meeting');const f=$('#editor');f.elements.capacity.closest('label').hidden=t!=='class';f.elements.service.closest('label').classList.toggle('hidden',!['class','one','room'].includes(t));if(!['class','one'].includes(t))f.elements.visibility.value='internal';else f.elements.visibility.value='members';if(t==='one'){f.elements.capacity.value=1;f.elements.capacity.readOnly=true}else f.elements.capacity.readOnly=false;}",
  " $('#editType').onchange=typeFields;$('#editService').onchange=()=>{const v=services.find(x=>x.id===$('#editService').value);if(v){const f=$('#editor');f.elements.title.value=v.name;f.elements.type.value=v.type;f.elements.duration.value=v.duration;f.elements.capacity.value=v.capacity;typeFields()}};typeFields();",
  "}",
  "function checkAndApply(next,focus,from,title,detail){",
  " const conflicts=E.newConflicts(state,next,E.add(from,-7),E.add(from,364));",
  " if(conflicts.length)throw Error('Not saved. Conflict on '+label(conflicts[0].date)+': '+conflicts[0].message+(conflicts.length>1?' ('+conflicts.length+' overlapping occurrences.)':''));",
  "  const events=E.occurrences(next,from,E.add(from,364));",
  " for(const e of events){E.validate(e);const old=E.occurrences(state,e.date,e.date).find(x=>x.key===e.key);if(old&&JSON.stringify(old)===JSON.stringify(e))continue;for(const c of E.resources(e)){if(availability[c]&&(e.start<availability[c].start||e.start+e.duration>availability[c].end))throw Error('Not saved: outside '+c+'’s staff hours. Adjust the booking or Team & rooms availability.');}}",
  " state=next;selected=focus;anchor=from;closeDialog();render();log(title,detail);toast(title);",
  "}",
  "function commit(e,patch,scope,deleting,notify){",
  " const affected=E.occurrences(state,e.originDate,E.add(e.originDate,364)).filter(x=>scope==='single'?x.key===e.key:x.ruleId===e.ruleId);",
  " const recipients=[...new Set(affected.flatMap(x=>[...E.resources(x),...memberClients(x)]).concat(patch.coach||[],patch.staff||[]))];",
  " const out=E.stage(state,e,patch,scope,deleting);checkAndApply(out.state,out.focus,patch.date||e.date,deleting?'Booking deleted':'Booking updated',e.title+' · '+scope);",
  " if(notify)log('Notification preview — nothing sent',`${e.title}: ${deleting?'cancelled':'changed'} (${scope}). Recipients: ${recipients.join(', ')||'No recipients'}.`);",
  "}",
  "function confirmChange(e,patch,deleting=false){openDialog(deleting?'Delete booking?':'Confirm calendar change',`<div class=\"note\">${esc(e.title)}<br>${label(e.date)} · ${time(e.start)}–${time(e.start+e.duration)}${!deleting?`<br><strong>→ ${label(patch.date||e.date)} · ${time(patch.start??e.start)}–${time((patch.start??e.start)+(patch.duration??e.duration))}</strong>${patch.coach?'<br>Coach: '+esc(patch.coach):''}${patch.room?'<br>Room: '+esc(patch.room):''}`:''}</div>${scopeHTML(e)}${notifyHTML()}<p class=\"sub\">Conflict checks cover 52 weeks from this occurrence.</p>`,()=>commit(e,patch,$('#editor').elements.scope?.value||'single',deleting,$('#editor').elements.notify.checked),deleting?'Delete booking':'Confirm change')}",
  "function draftMessage(e){const recipients=[...new Set([...E.resources(e),...memberClients(e)])];openDialog('Draft a session message',`<p class=\"sub\">Demo recipients: ${esc(recipients.join(', ')||'No recipients')}</p>${field('message','Message','<textarea required maxlength=\"2000\" placeholder=\"Write a session update…\"></textarea>')}<p class=\"note\">Preview only. No email, SMS or push notification will be sent.</p>`,()=>{log('Message preview — nothing sent',$('#editor').elements.message.value+' | To: '+recipients.join(', '));closeDialog();toast('Message preview saved in Activity.')},'Save preview')}",
  "function startDrag(ev){",
  " if(pendingDrag||isMember()||ev.button!==0||ev.target.closest('.grip')===null&&ev.pointerType!=='mouse'&&!ev.target.closest('.resize'))return;",
  " const card=ev.target.closest('.event'),e=all.find(x=>x.key===card.dataset.key);if(!e)return;",
  " drag={e,card,lane:card.closest('.lane'),resize:!!ev.target.closest('.resize'),x:ev.clientX,y:ev.clientY,px:ev.clientX,py:ev.clientY,id:ev.pointerId,active:false,offset:ev.clientY-card.getBoundingClientRect().top};",
  " // Preserve normal clicks. Dragging starts only after the pointer moves.",
  "}",
  "function paintDrag(){",
  " const d=drag;if(!d?.active)return;const scroll=$('#calendarScroll'),bounds=scroll.getBoundingClientRect();",
  " const inside=d.px>=bounds.left&&d.px<=bounds.right&&d.py>=bounds.top&&d.py<=bounds.bottom;",
  " if(inside){const edge=42;const speed=(p,min,max)=>p<min+edge?-Math.ceil((min+edge-p)/4):p>max-edge?Math.ceil((p-max+edge)/4):0;scroll.scrollTop+=speed(d.py,bounds.top+57,bounds.bottom);if(!d.resize)scroll.scrollLeft+=speed(d.px,bounds.left,bounds.right)}",
  " const hit=inside?document.elementFromPoint(d.px,d.py)?.closest('.lane'):null;d.target=null;",
  " $$('.lane.dragover').forEach(el=>el.classList.remove('dragover'));",
  " if(hit){",
  "  const lane=d.resize?d.lane:hit;lane.classList.add('dragover');const rect=lane.getBoundingClientRect();",
  "  if(d.resize){const raw=Math.max(15,Math.min(1200-d.e.start,(d.py-rect.top)/1.2+360-d.e.start));const duration=Math.max(15,Math.min(1200-d.e.start,Math.round(raw/15)*15));d.target={duration};d.card.style.height=(raw*1.2-4)+'px'}",
  "  else{const raw=Math.max(360,Math.min(1200-d.e.duration,360+(d.py-rect.top-d.offset)/1.2));d.target={date:lane.dataset.date,start:Math.round(raw/15)*15,...(lane.dataset.coach?{coach:lane.dataset.coach}:{}),...(lane.dataset.room?{room:lane.dataset.room}:{})};if(d.card.parentElement!==lane)lane.append(d.card);d.card.style.top=(raw-360)*1.2+2+'px';d.card.style.left='3px';d.card.style.width='calc(100% - 6px)'}",
  "  const start=d.target.start??d.e.start,duration=d.target.duration??d.e.duration;d.card.querySelector('.eventmain > small').textContent=time(start)+'–'+time(start+duration);",
  " }",
  " d.card.classList.toggle('invalid-drop',!d.target);d.frame=requestAnimationFrame(paintDrag);",
  "}",
  "document.addEventListener('pointermove',ev=>{",
  " if(!drag||ev.pointerId!==drag.id)return;drag.px=ev.clientX;drag.py=ev.clientY;",
  " if(!drag.active&&Math.hypot(ev.clientX-drag.x,ev.clientY-drag.y)<6)return;",
  " ev.preventDefault();if(!drag.active){drag.active=true;drag.card.classList.add('live-drag');document.body.classList.add('dragging');paintDrag()}",
  "},{passive:false});",
  "function finishDrag(ev,cancel=false){",
  " if(!drag||ev.pointerId!==drag.id)return;const d=drag;",
  " if(d.active&&!cancel){d.px=ev.clientX??d.px;d.py=ev.clientY??d.py;cancelAnimationFrame(d.frame);paintDrag()}",
  " cancelAnimationFrame(d.frame);drag=null;document.body.classList.remove('dragging');$$('.lane.dragover').forEach(el=>el.classList.remove('dragover'));",
  " if(!d.active)return;window.suppressClickUntil=Date.now()+500;",
  " if(cancel||!d.target){render();return}",
  " if(d.e.type==='meeting'&&view==='coaches'&&!d.resize){render();toast('Move team meetings in Day or Week view to keep all staff attendees.');return}",
  " if(Object.entries(d.target).every(([k,v])=>d.e[k]===v)){render();return}",
  " // Keep the preview on the calendar; commit the data only after confirmation.",
  " d.card.classList.remove('live-drag','invalid-drop');d.card.classList.add('pending-move');",
  " d.card.style.top=((d.target.start??d.e.start)-360)*1.2+2+'px';d.card.style.height=(d.target.duration??d.e.duration)*1.2-4+'px';",
  " pendingDrag=d;",
  " // Let the dropped position paint before the confirmation appears.",
  " requestAnimationFrame(()=>requestAnimationFrame(()=>{if(pendingDrag===d)confirmChange(d.e,d.target)}));",
  "}",
  "document.addEventListener('pointerup',e=>finishDrag(e));document.addEventListener('pointercancel',e=>finishDrag(e,true));",
  "window.addEventListener('blur',()=>{if(drag)finishDrag({pointerId:drag.id},true)});",
  "document.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){finishDrag({pointerId:drag.id},true)}else if(e.key==='Escape'&&pendingDrag&&!$('#dialog').open){pendingDrag=null;render()}});",
  "$('#dialog').addEventListener('cancel',e=>{e.preventDefault();closeDialog()});",
  "function renderPage(){const root=$('#otherPage');root.className='pagecontent';if(page==='services'){root.innerHTML=`<div class=\"pagehead\"><div><h2>Services & classes</h2><p class=\"sub\">Reusable templates. Sessions reserve staff and rooms separately.</p></div><button id=\"newService\" class=\"primary\">＋ New service</button></div><div class=\"cards\">${services.map(s=>`<article class=\"card\"><span class=\"eyebrow\">${esc(types[s.type])}</span><h3 style=\"margin-top:9px\">${esc(s.name)}</h3><p>${s.duration} minutes · ${s.capacity} ${s.capacity===1?'client':'spots'}<br>$${s.price} drop-in · ${s.cancel}h cancellation window</p><div class=\"cardfoot\"><span>Template</span><button data-edit-service=\"${s.id}\">Edit</button></div></article>`).join('')}</div>`;$('#newService').onclick=()=>editService();$$('[data-edit-service]').forEach(b=>b.onclick=()=>editService(services.find(s=>s.id===b.dataset.editService)))}",
  " if(page==='staff'){root.innerHTML=`<div class=\"pagehead\"><div><h2>Team & rooms</h2><p class=\"sub\">Regular daily staff hours. Add calendar blocks for time off and room maintenance.</p></div><button id=\"newBlock\" class=\"primary\">＋ Block time</button></div><div class=\"cards\">${coaches.map(c=>`<article class=\"card\"><span class=\"avatar\">${initials(c)}</span><h3 style=\"margin-top:12px\">${esc(c)}</h3><p>${time(availability[c].start)}–${time(availability[c].end)}<br>Applied daily in this demo</p><button data-hours=\"${esc(c)}\">Edit hours</button></article>`).join('')}</div><h2 style=\"margin:28px 0 16px\">Rooms</h2><div class=\"cards\">${rooms.map(r=>`<article class=\"card\"><h3>${esc(r)}</h3><p>Exclusive reservations · detects overlapping sessions and maintenance blocks.</p><button data-room-view=\"${esc(r)}\">View bookings</button></article>`).join('')}</div>`;$('#newBlock').onclick=()=>editBooking(null,{type:'block',title:'Time off / maintenance',room:'',visibility:'internal'});$$('[data-hours]').forEach(b=>b.onclick=()=>editHours(b.dataset.hours));$$('[data-room-view]').forEach(b=>b.onclick=()=>{page='calendar';view='rooms';$('#roomFilter').value=b.dataset.roomView;render()});}",
  " if(page==='settings'){root.innerHTML=`<div class=\"pagehead\"><h2>Booking settings</h2></div><div class=\"card\">${[['waitlist','Waitlists','Full sessions accept waitlisted members. Cancellation promotes the first eligible member.'],['notify','Notification previews by default','Calendar changes generate a recipient preview, never a real message.'],['zero','Zero-booking alerts','Show the simulated coach alert on empty sessions.'],['mobile','Mobile app bookings','Demo setting only; this prototype is not connected to the Milton app.'],['public','Public booking page','Demo setting only; this does not publish or share this private prototype.']].map(([key,t,sub])=>`<label class=\"setting\"><div><strong>${t}</strong><small>${sub}</small></div><input data-setting=\"${key}\" type=\"checkbox\" ${settings[key]?'checked':''}></label>`).join('')}<p class=\"note\">Package policy in this demo: booking requires a positive credit balance. One credit is consumed at check-in, not on booking; no-shows do not consume a credit. No payment is processed.</p></div>`;$$('[data-setting]').forEach(x=>x.onchange=()=>{settings[x.dataset.setting]=x.checked;log('Demo setting changed',x.dataset.setting+' = '+x.checked);toast('Demo setting updated.')});}",
  " if(page==='activity'){root.innerHTML=`<div class=\"pagehead\"><div><h2>Activity & notification previews</h2><p class=\"sub\">Everything here is simulated. No real messages or payments.</p></div></div>${activity.map(a=>`<article class=\"activity\"><strong>${esc(a.title)}</strong><p>${esc(a.detail)}</p><small>${esc(a.at)}</small></article>`).join('')||'<div class=\"card\">No activity yet. Edit a booking, check in a member or preview a message.</div>'}`;}}",
  "function editService(s){const v=s||{name:'',type:'class',duration:45,capacity:6,price:35,cancel:12};openDialog(s?'Edit service':'New service',`<div class=\"formgrid\">${field('name','Service name',`<input required maxlength=\"80\" value=\"${esc(v.name)}\">`,true)}${field('type','Type',`<select>${option('class','Class',v.type)+option('one','1:1',v.type)}</select>`)}${field('duration','Duration (minutes)',`<input required type=\"number\" min=\"15\" max=\"240\" step=\"15\" value=\"${v.duration}\">`)}${field('capacity','Capacity',`<input required type=\"number\" min=\"1\" max=\"50\" value=\"${v.capacity}\">`)}${field('price','Drop-in price ($)',`<input required type=\"number\" min=\"0\" value=\"${v.price}\">`)}${field('cancel','Cancellation window (hours)',`<input required type=\"number\" min=\"0\" value=\"${v.cancel}\">`)}</div><p class=\"sub\">Template edits apply to new bookings; existing sessions keep their settings.</p>`,()=>{const f=$('#editor').elements;const data={id:s?.id||E.uid(),name:f.name.value.trim(),type:f.type.value,duration:Number(f.duration.value),capacity:f.type.value==='one'?1:Number(f.capacity.value),price:Number(f.price.value),cancel:Number(f.cancel.value)};if(!data.name)throw Error('Enter a service name.');if(s)Object.assign(s,data);else services.push(data);closeDialog();render();log('Service template saved',data.name);toast('Service saved.')})}",
  "function editHours(c){openDialog('Availability • '+c,`<div class=\"formgrid\">${field('start','Daily start',`<input type=\"time\" required value=\"${timeInput(availability[c].start)}\">`)}${field('end','Daily end',`<input type=\"time\" required value=\"${timeInput(availability[c].end)}\">`)}</div><p class=\"sub\">Existing sessions stay scheduled. New or changed bookings are checked against these hours. Use blocked time for individual days off.</p>`,()=>{const f=$('#editor').elements,start=minutes(f.start.value),end=minutes(f.end.value);if(end<=start)throw Error('End must be after start.');availability[c]={start,end};closeDialog();render();log('Staff hours updated',c+' · '+time(start)+'–'+time(end));toast('Availability updated.')})}",
  "$('#editor').onsubmit=e=>{e.preventDefault();$('#formError').textContent='';try{submitAction?.()}catch(err){$('#formError').textContent=err.message}};",
  "$('#closeDialog').onclick=closeDialog;$('#cancelDialog').onclick=closeDialog;",
  "$('#newEvent').onclick=()=>editBooking();",
  "$$('[data-page]').forEach(b=>b.onclick=()=>{if(isMember()&&b.dataset.page!=='calendar'){toast('Switch to Staff calendar to manage settings.');return}page=b.dataset.page;render()});",
  "$$('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;selected=null;render()});",
  "['typeFilter','coachFilter','roomFilter','colorBy','member'].forEach(id=>$('#'+id).onchange=()=>{selected=null;render()});",
  "$('#audience').onchange=()=>{if(isMember()){view='week';page='calendar';$('#typeFilter').value='all';$('#coachFilter').value='all';$('#roomFilter').value='all'}selected=null;render()};",
  "function navigate(n){if(view==='month'){const d=E.date(anchor);d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+n);anchor=E.iso(d)}else anchor=E.add(anchor,n*(view==='week'?7:1));selected=null;render();}",
  "$('#prev').onclick=()=>navigate(-1);$('#next').onclick=()=>navigate(1);$('#today').onclick=()=>{anchor=localToday();selected=null;render()};",
  "document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#dialog').open&&!drag&&!pendingDrag){selected=null;$('#detail').classList.add('hidden')}});",
  "function enhanceSetup(){if(!['settings','staff'].includes(page))return;",
  " const tabs=document.createElement('div');tabs.className='setup-tabs';tabs.innerHTML=`<button data-setup=\"settings\" class=\"${page==='settings'?'active':''}\">Hours & booking settings</button><button data-setup=\"staff\" class=\"${page==='staff'?'active':''}\">Team & Rooms</button>`;$('#otherPage').prepend(tabs);tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{page=b.dataset.setup;render()});if(page!=='settings')return;",
  " const root=$('#otherPage');root.querySelector('.pagehead h2').textContent='Scheduling settings';",
  " const setup=document.createElement('div');setup.innerHTML=`<article class=\"card setup-card\"><h3>Connected calendars</h3><p>Calendar connections are examples only. This prototype does not sync external events.</p><div class=\"setting\"><div><strong>Rolland Cheng</strong><small>Google Calendar</small></div><span class=\"badge\">Demo connection</span></div><div class=\"setting\"><div><strong>Hayden Guzinski</strong><small>Outlook</small></div><span class=\"badge\">Demo connection</span></div><button id=\"connectCalendar\">＋ Connect calendar</button></article><article class=\"card setup-card\"><h3>Hours</h3><p>Set a shared daily window for your team. Individual coach hours can be adjusted in Team & Rooms.</p><p>Classes keep their explicit start times. Hours never generate a class timetable.</p><button id=\"businessHours\">Edit team-wide hours</button></article>`;",
  " root.querySelector('.pagehead').after(setup);",
  " $('#connectCalendar').onclick=()=>openDialog('Connect a calendar',`<p>In Milton, this is where a coach would authorize Google, Outlook or Apple calendar access.</p><p class=\"note\">Connections are not available in this prototype. No credentials are requested or stored.</p>`,closeDialog,'Got it');",
  " $('#businessHours').onclick=()=>openDialog('Team-wide daily hours',`<p class=\"sub\">Apply a shared daily window to every coach in this demo. This replaces their individual daily hours. Existing sessions stay scheduled.</p><div class=\"formgrid\">${field('start','Opening time','<input type=\"time\" required value=\"06:00\">')}${field('end','Closing time','<input type=\"time\" required value=\"20:00\">')}</div><p class=\"note\">Day-specific business hours and holidays are not modeled here. Use calendar blocks for exceptions.</p>`,()=>{const f=$('#editor').elements,start=minutes(f.start.value),end=minutes(f.end.value);if(end<=start)throw Error('Closing time must be after opening time.');for(const c of coaches)availability[c]={start,end};closeDialog();render();log('Team-wide daily hours updated',time(start)+'–'+time(end));toast('Hours updated for every coach.')},'Apply to all coaches');",
  "}",
  "const originalEditService=editService;",
  "editService=function(s){originalEditService(s);const grid=$('#dialogBody .formgrid');const details=document.createElement('details');details.className='advanced-fields';details.innerHTML='<summary>Pricing & cancellation rules</summary><div class=\"formgrid\"></div>';for(const name of ['price','cancel'])details.querySelector('div').append($('#editor').elements[name].closest('label'));grid.after(details);const type=$('#editor').elements.type,cap=$('#editor').elements.capacity;const update=()=>cap.closest('label').hidden=type.value==='one';type.onchange=update;update();};",
  "function bookingPreview(step=0,choice={}){",
  " const steps=['Service','Date','Time','Confirm'];const trail=`<div class=\"booking-steps\">${steps.map((s,i)=>`<span class=\"${i===step?'current':''}\">${i+1} ${s}</span>`).join('')}</div>`;",
  " const member=choice.member||chosenMember()||clients[0].name;",
  " if(step===0){openDialog('What would you like to book?',trail+field('previewMember','Preview as member',`<select id=\"previewMember\">${clients.map(c=>option(c.name,c.name+' · '+creditBalance(c.name)+' credits',member)).join('')}</select>`)+`<div class=\"booking-options\" style=\"margin-top:20px\">${services.filter(s=>['class','one'].includes(s.type)).map(s=>`<button type=\"button\" data-book-service=\"${s.id}\"><strong>${esc(s.name)}</strong><small>${s.duration} min · ${s.type==='class'?s.capacity+' spots':'1 person'} · 1 demo credit</small></button>`).join('')}</div><p class=\"sub\">Uses this demo’s sample sessions. Room reservations currently use the staff calendar.</p>`,closeDialog,'Close preview');$$('[data-book-service]').forEach(b=>b.onclick=()=>bookingPreview(1,{service:b.dataset.bookService,member:$('#previewMember').value}));return}",
  " const service=services.find(s=>s.id===choice.service);",
  " if(step===1){openDialog('Choose a date',trail+`<p>${esc(service.name)}</p>`+field('bookingDate','Date',`<input id=\"bookingDate\" type=\"date\" required value=\"${choice.date||anchor}\">`)+`<p class=\"sub\">Choose a date to see available classes and appointments.</p>`,()=>bookingPreview(2,{...choice,date:$('#bookingDate').value}),'Show times');return}",
  " if(step===2){const matches=E.occurrences(state,choice.date,choice.date).filter(e=>e.service===choice.service&&e.visibility==='members'&&['class','one'].includes(e.type)&&!e.roster.some(r=>r.member===member)&&(e.type!=='one'||booked(e).length<e.capacity));openDialog('Choose a time',trail+`<p>${esc(service.name)} · ${label(choice.date)}</p><div class=\"booking-options\">${matches.map(e=>`<button type=\"button\" data-book-time=\"${esc(e.key)}\"><strong>${time(e.start)}–${time(e.start+e.duration)}</strong><small>${esc(e.coach)} · ${esc(e.room)} · ${Math.max(0,e.capacity-booked(e).length)} spots${booked(e).length>=e.capacity?' · Waitlist':''}</small></button>`).join('')||'<p>No sessions available on this date. Try a different date.</p>'}</div>`,()=>bookingPreview(1,choice),'Change date');$$('[data-book-time]').forEach(b=>b.onclick=()=>bookingPreview(3,{...choice,key:b.dataset.bookTime}));return}",
  " const e=E.occurrences(state,choice.date,choice.date).find(e=>e.key===choice.key);if(!e){bookingPreview(2,choice);return}",
  " openDialog('Confirm your booking',trail+`<h3>${esc(e.title)}</h3><p>${label(e.date,{weekday:'long',month:'long',day:'numeric'})}<br>${time(e.start)}–${time(e.start+e.duration)}</p><p>${esc(e.coach)} · ${esc(e.room)}</p><div class=\"note\">${esc(member)} · ${creditBalance(member)} credits available<br>One demo credit is used at check-in. ${booked(e).length>=e.capacity?'This session is full; you will join the waitlist.':''}</div>`,()=>{if(creditBalance(member)<=0)throw Error('No eligible credits. Choose a member with credits.');if(overlapsMember(e,member))throw Error('You already have a booking at this time. Choose another time.');if(!addMember(e,member))throw Error('Unable to book. Check credits, capacity and availability.');openDialog('You’re on the schedule',`<h3>${esc(e.title)}</h3><p>${esc(member)} · ${label(e.date)} · ${time(e.start)}</p><p class=\"note\">${booked(e).length>=e.capacity?'Added to the demo waitlist.':'Demo booking confirmed.'} No real payment or notification was sent.</p>`,()=>{closeDialog();page='calendar';view='day';anchor=e.date;selected=e.key;render()},'View in calendar')},booked(e).length>=e.capacity?'Join waitlist':'Confirm booking');",
  "}",
  "$('#previewBooking').onclick=()=>bookingPreview();",
  "$('#shareBooking').onclick=()=>openDialog('Share & embed',`<p>Your member booking link and website embed would live here in Milton.</p><p class=\"note\">This is a private prototype. Public booking links and embeds are not connected, and this action does not change who can access it.</p>`,()=>bookingPreview(),'Preview booking flow');",
  "seed();populateFilters();render();",
  "// Existing page-level agent tools use the same validation and calendar state as UI actions.",
  "if(document.modelContext?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(document.modelContext.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}};",
  "register({name:'list_schedule_sessions',description:'Read bookings in the selected calendar period.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){return{sessions:visible.map(e=>({id:e.key,title:e.title,date:e.date,start:e.start,duration:e.duration,type:e.type,coach:e.coach,room:e.room,booked:booked(e).length,capacity:e.capacity}))}}});",
  "register({name:'create_schedule_session',description:'Create one non-recurring class with conflict validation in the demo only.',inputSchema:{type:'object',properties:{service:{type:'string'},date:{type:'string'},hour:{type:'integer',minimum:6,maximum:19},minute:{type:'integer',minimum:0,maximum:59},coach:{type:'string'},capacity:{type:'integer',minimum:1,maximum:50},location:{type:'string'}},required:['service','date','hour','coach','capacity','location'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!coaches.includes(input.coach)||!rooms.includes(input.location))throw Error('Unknown staff or room');const svc=services.find(s=>s.name===input.service);if(!svc)throw Error('Unknown service');const p={title:svc.name,type:svc.type,date:input.date,start:input.hour*60+(input.minute||0),duration:svc.duration,coach:input.coach,room:input.location,capacity:input.capacity,roster:[],staff:[],repeat:false,visibility:'members',service:svc.id};const out=E.stage(state,null,p);checkAndApply(out.state,out.focus,p.date,'Booking created',p.title);return{id:out.focus,status:'created'}}});",
  "register({name:'reassign_session_coach',description:'Reassign a single occurrence, with conflict validation; no message is sent.',inputSchema:{type:'object',properties:{sessionId:{type:'string'},coach:{type:'string'}},required:['sessionId','coach'],additionalProperties:false},annotations:{readOnlyHint:false},execute(i){if(!coaches.includes(i.coach))throw Error('Unknown coach');const e=all.find(e=>e.key===i.sessionId);if(!e)throw Error('Session not in current calendar period');commit(e,{coach:i.coach},'single',false,false);return{id:e.key,coach:i.coach,status:'updated'}}});}",
  "})();",
  ""
].join("\n");

const SCHEDULE_DOCUMENT = '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Milton Schedule</title><style>' + WORKSPACE_CSS + '</style></head><body>' + WORKSPACE_HTML + '<script>' + SCHEDULE_ENGINE + '</script><script>' + SCHEDULE_APP + '</script></body></html>';
